//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Message: Codable {

    public var body: String?
    public var createdTime: String?
    public var user: User?

    public init(body: String? = nil, createdTime: String? = nil, user: User? = nil) {
        self.body = body
        self.createdTime = createdTime
        self.user = user
    }


}
