//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: Int?
    public var displayName: String?
    public var presence: Presence?
    public var type: String?

    public init(_id: Int? = nil, displayName: String? = nil, presence: Presence? = nil, type: String? = nil) {
        self._id = _id
        self.displayName = displayName
        self.presence = presence
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case presence
        case type
    }

}
