//
// ApiError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApiError: Codable {

    public var error: String
    public var explanation: String?
    public var message: String
    public var properties: AnyCodable?
    public var timestamp: String

    public init(error: String, explanation: String? = nil, message: String, properties: AnyCodable? = nil, timestamp: String) {
        self.error = error
        self.explanation = explanation
        self.message = message
        self.properties = properties
        self.timestamp = timestamp
    }


}
