//
// ApplicationJobResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApplicationJobResource: Codable {

    public enum ModelType: String, Codable { 
        case channelImport = "CHANNEL_IMPORT"
        case channelMembersImport = "CHANNEL_MEMBERS_IMPORT"
        case messageImport = "MESSAGE_IMPORT"
        case userImport = "USER_IMPORT"
    }
    public enum State: String, Codable { 
        case pending = "PENDING"
        case running = "RUNNING"
        case finished = "FINISHED"
        case failed = "FAILED"
    }
    /** The type of application job */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    public var createdTime: Date
    public var endedTime: Date?
    /** The running state of an application job */
    public var state: State
    public var links: Links?

    public init(type: ModelType, _id: Int64, createdTime: Date, endedTime: Date? = nil, state: State, links: Links? = nil) {
        self.type = type
        self._id = _id
        self.createdTime = createdTime
        self.endedTime = endedTime
        self.state = state
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case createdTime
        case endedTime
        case state
        case links = "_links"
    }

}
