//
// ApplicationSettingsResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApplicationSettingsResource: Codable {

    public enum GuestUsers: String, Codable { 
        case disabled = "DISABLED"
        case enabled = "ENABLED"
    }
    public enum UserCreatedChannels: String, Codable { 
        case disabled = "DISABLED"
        case enabled = "ENABLED"
    }
    /** Toggle state of this settings option */
    public var guestUsers: GuestUsers
    /** Toggle state of this settings option */
    public var userCreatedChannels: UserCreatedChannels
    public var links: Links?

    public init(guestUsers: GuestUsers, userCreatedChannels: UserCreatedChannels, links: Links? = nil) {
        self.guestUsers = guestUsers
        self.userCreatedChannels = userCreatedChannels
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case guestUsers
        case userCreatedChannels
        case links = "_links"
    }

}
