//
// AuthenticationError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthenticationError: Codable {

    public var error: String
    public var errorDescription: String

    public init(error: String, errorDescription: String) {
        self.error = error
        self.errorDescription = errorDescription
    }

    public enum CodingKeys: String, CodingKey { 
        case error
        case errorDescription = "error_description"
    }

}
