//
// ChannelImport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelImport: Codable {

    public var type: String
    /** Username of the user who created this channel */
    public var creator: String?
    /** Unique value generated by the client which ChatKitty uses to recognize subsequent retries of the same request. Optional but recommended */
    public var idempotencyKey: String?
    /** List of usernames of members of this channel */
    public var members: [String]
    /** Custom data associated with this channel */
    public var properties: AnyCodable?

    public init(type: String, creator: String? = nil, idempotencyKey: String? = nil, members: [String], properties: AnyCodable? = nil) {
        self.type = type
        self.creator = creator
        self.idempotencyKey = idempotencyKey
        self.members = members
        self.properties = properties
    }


}
