//
// ChannelGenericEventResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelGenericEventResource: Codable {

    /** Custom type of this event */
    public var type: String
    /** Custom data associated with this event */
    public var properties: AnyCodable
    public var user: ChatUserProperties?
    public var links: Links?

    public init(type: String, properties: AnyCodable, user: ChatUserProperties? = nil, links: Links? = nil) {
        self.type = type
        self.properties = properties
        self.user = user
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case properties
        case user
        case links = "_links"
    }

}
