//
// ChannelResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelResource: Codable {

    public enum ModelType: String, Codable { 
        case direct = "DIRECT"
        case _public = "PUBLIC"
        case _private = "PRIVATE"
    }
    /** The type of this channel */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The ISO date-time this channel was created */
    public var createdTime: Date
    public var creator: ChatUserProperties?
    public var lastReceivedMessage: MessageProperties?
    /** Custom data associated with this channel */
    public var properties: AnyCodable
    public var links: Links?

    public init(type: ModelType, _id: Int64, createdTime: Date, creator: ChatUserProperties? = nil, lastReceivedMessage: MessageProperties? = nil, properties: AnyCodable, links: Links? = nil) {
        self.type = type
        self._id = _id
        self.createdTime = createdTime
        self.creator = creator
        self.lastReceivedMessage = lastReceivedMessage
        self.properties = properties
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case createdTime
        case creator
        case lastReceivedMessage
        case properties
        case links = "_links"
    }

}
