//
// ChannelMembershipImport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelMembershipImport: Codable {

    /** Unique value generated by the client which ChatKitty uses to recognize subsequent retries of the same request. Optional but recommended */
    public var idempotencyKey: String?
    /** Username of the user to be added as a member */
    public var username: String

    public init(idempotencyKey: String? = nil, username: String) {
        self.idempotencyKey = idempotencyKey
        self.username = username
    }


}
