//
// ChatFunctionResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatFunctionResource: Codable {

    /** The type of this function */
    public var type: String
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The current version number of this function. Incremented every time a new version is deployed */
    public var currentVersionNumber: Int64
    /** Optional description of this function */
    public var _description: String?
    /** True if this function is enabled */
    public var enabled: Bool
    /** The name of this function */
    public var name: String
    public var runtime: ChatFunctionChatRuntimeProperties
    public var links: Links?

    public init(type: String, _id: Int64, currentVersionNumber: Int64, _description: String? = nil, enabled: Bool, name: String, runtime: ChatFunctionChatRuntimeProperties, links: Links? = nil) {
        self.type = type
        self._id = _id
        self.currentVersionNumber = currentVersionNumber
        self._description = _description
        self.enabled = enabled
        self.name = name
        self.runtime = runtime
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case currentVersionNumber
        case _description = "description"
        case enabled
        case name
        case runtime
        case links = "_links"
    }

}
