//
// ChatUserUsernameReference.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Reference to a user by username */

public struct ChatUserUsernameReference: Codable {

    /** Username associated with this user */
    public var username: String

    public init(username: String) {
        self.username = username
    }


}
