//
// ChatSessionResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatSessionResource: Codable {

    public enum State: String, Codable { 
        case active = "ACTIVE"
        case ended = "ENDED"
    }
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** Time this session was created */
    public var createdTime: Date
    /** Time this session ended. Present if state is ENDED */
    public var endTime: Date?
    public var session: ChatUserSessionProperties
    /** State of this session. ACTIVE or ENDED */
    public var state: State
    public var links: Links?

    public init(_id: Int64, createdTime: Date, endTime: Date? = nil, session: ChatUserSessionProperties, state: State, links: Links? = nil) {
        self._id = _id
        self.createdTime = createdTime
        self.endTime = endTime
        self.session = session
        self.state = state
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdTime
        case endTime
        case session
        case state
        case links = "_links"
    }

}
