//
// ChatFunctionChatRuntimeProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The runtime this function executes on. Always a NodeJS runtime */

public struct ChatFunctionChatRuntimeProperties: Codable {

    public enum ModelType: String, Codable { 
        case nodejs = "NODEJS"
    }
    /** The type of this runtime. Always NODEJS */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The semantic version of this runtime */
    public var version: String

    public init(type: ModelType, _id: Int64, version: String) {
        self.type = type
        self._id = _id
        self.version = version
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case version
    }

}
