//
// ChatUserPresencePropertiesPatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Updates the presence status of this user */

public struct ChatUserPresencePropertiesPatch: Codable {

    /** Updates the availability status of this user */
    public var status: String?

    public init(status: String? = nil) {
        self.status = status
    }


}
