//
// ChatFunctionInvocationResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatFunctionInvocationResource: Codable {

    public enum Status: String, Codable { 
        case running = "RUNNING"
        case succeeded = "SUCCEEDED"
        case failed = "FAILED"
    }
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The function arguments passed into this function for this invocation */
    public var args: AnyCodable
    /** The ISO date-time of this invocation when the function was called */
    public var createdTime: Date
    /** The result of this invocation when it completed */
    public var result: AnyCodable
    /** The running status of this invocation */
    public var status: Status
    /** The version number of this function version when this invocation occured */
    public var versionNumber: Int64
    public var links: Links?

    public init(_id: Int64, args: AnyCodable, createdTime: Date, result: AnyCodable, status: Status, versionNumber: Int64, links: Links? = nil) {
        self._id = _id
        self.args = args
        self.createdTime = createdTime
        self.result = result
        self.status = status
        self.versionNumber = versionNumber
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case args
        case createdTime
        case result
        case status
        case versionNumber
        case links = "_links"
    }

}
