//
// ChatUserResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatUserResource: Codable {

    public enum ModelType: String, Codable { 
        case person = "PERSON"
        case bot = "BOT"
    }
    public enum CallStatus: String, Codable { 
        case available = "AVAILABLE"
        case inCall = "IN_CALL"
    }
    /** Type of user */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** Call presence status of this user */
    public var callStatus: CallStatus?
    /** Human readable name of this user. Shown to other users */
    public var displayName: String
    /** URL for this user&#x27;s display picture */
    public var displayPictureUrl: String
    /** True if this user was created by a guest user session */
    public var isGuest: Bool
    /** The unique name used to identify this user across ChatKitty. Also known as username */
    public var name: String
    public var presence: ChatUserPresenceProperties
    /** Custom data associated with this user */
    public var properties: AnyCodable
    public var links: Links?

    public init(type: ModelType, _id: Int64, callStatus: CallStatus? = nil, displayName: String, displayPictureUrl: String, isGuest: Bool, name: String, presence: ChatUserPresenceProperties, properties: AnyCodable, links: Links? = nil) {
        self.type = type
        self._id = _id
        self.callStatus = callStatus
        self.displayName = displayName
        self.displayPictureUrl = displayPictureUrl
        self.isGuest = isGuest
        self.name = name
        self.presence = presence
        self.properties = properties
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case callStatus
        case displayName
        case displayPictureUrl
        case isGuest
        case name
        case presence
        case properties
        case links = "_links"
    }

}
