//
// ChatRuntimeDependencyProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The NPM dependencies version of this runtime */

public struct ChatRuntimeDependencyProperties: Codable {

    /** True if this NPM package is automatically installed by ChatKitty and available by default in your chat functions */
    public var defaultDependency: Bool
    /** The name of the dependency NPM package */
    public var name: String
    /** The version of the NPM package */
    public var version: String

    public init(defaultDependency: Bool, name: String, version: String) {
        self.defaultDependency = defaultDependency
        self.name = name
        self.version = version
    }


}
