//
// ChatRuntimeResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRuntimeResource: Codable {

    public enum ModelType: String, Codable { 
        case nodejs = "NODEJS"
    }
    /** The type of this runtime. Always NODEJS */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The NPM dependencies version of this runtime */
    public var dependencies: [ChatRuntimeDependencyProperties]
    /** Environment variable set for this runtime. Accessible in the initialization script and chat functions associated with this runtime */
    public var environmentVariables: AnyCodable
    public var initializationScript: ChatRuntimeScriptProperties?
    /** The semantic version of this runtime */
    public var version: String
    public var links: Links?

    public init(type: ModelType, _id: Int64, dependencies: [ChatRuntimeDependencyProperties], environmentVariables: AnyCodable, initializationScript: ChatRuntimeScriptProperties? = nil, version: String, links: Links? = nil) {
        self.type = type
        self._id = _id
        self.dependencies = dependencies
        self.environmentVariables = environmentVariables
        self.initializationScript = initializationScript
        self.version = version
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case dependencies
        case environmentVariables
        case initializationScript
        case version
        case links = "_links"
    }

}
