//
// ChatUserRepliedToChatUserMessageNotificationData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Sent when a user replies to a message */

public struct ChatUserRepliedToChatUserMessageNotificationData: Codable {

    public var type: String
    /** The ID of channel the reply message was sent. Deprecated: Use the channel property of this notification */
    public var channelId: Int64
    public var message: MessageResource
    public var parent: MessageResource

    public init(type: String, channelId: Int64, message: MessageResource, parent: MessageResource) {
        self.type = type
        self.channelId = channelId
        self.message = message
        self.parent = parent
    }


}
