//
// ChatUserReference.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Reference to a user */

public struct ChatUserReference: Codable {




}
