//
// ChatUserSessionProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatUserSessionProperties: Codable {

    public enum State: String, Codable { 
        case active = "ACTIVE"
        case ended = "ENDED"
    }
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** Time this session was created */
    public var createdTime: Date
    /** Time this session ended. Present if state is ENDED */
    public var endTime: Date?
    /** State of this session. ACTIVE or ENDED */
    public var state: State
    public var user: ChatUserProperties
    /** User agent used to start this session */
    public var userAgent: String?

    public init(_id: Int64, createdTime: Date, endTime: Date? = nil, state: State, user: ChatUserProperties, userAgent: String? = nil) {
        self._id = _id
        self.createdTime = createdTime
        self.endTime = endTime
        self.state = state
        self.user = user
        self.userAgent = userAgent
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdTime
        case endTime
        case state
        case user
        case userAgent
    }

}
