//
// ChatRuntimeScriptProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRuntimeScriptProperties: Codable {

    /** The JavaScript/TypeScript source of this script */
    public var script: String

    public init(script: String) {
        self.script = script
    }


}
