//
// ChatUserMentionedChannelNotificationData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Sent when a user mentions a channel in a message */

public struct ChatUserMentionedChannelNotificationData: Codable {

    public var type: String
    /** The ID of the channel the mentioning message was sent. Deprecated: Use the channel property of this notification */
    public var channelId: Int64
    public var mentionedChannel: ChannelResource
    public var message: TextMessageResource

    public init(type: String, channelId: Int64, mentionedChannel: ChannelResource, message: TextMessageResource) {
        self.type = type
        self.channelId = channelId
        self.mentionedChannel = mentionedChannel
        self.message = message
    }


}
