//
// ChatFunctionVersionResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatFunctionVersionResource: Codable {

    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** JavaScript/TypeScript code that runs when this function is executed */
    public var handlerScript: String
    /** The version number of this function version. Incremented from the previous version */
    public var versionNumber: Int64
    public var links: Links?

    public init(_id: Int64, handlerScript: String, versionNumber: Int64, links: Links? = nil) {
        self._id = _id
        self.handlerScript = handlerScript
        self.versionNumber = versionNumber
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case handlerScript
        case versionNumber
        case links = "_links"
    }

}
