//
// CreateDelegatedReplyThreadKeystrokesResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateDelegatedReplyThreadKeystrokesResource: Codable {

    public var keys: String
    public var user: OneOfCreateDelegatedReplyThreadKeystrokesResourceUser

    public init(keys: String, user: OneOfCreateDelegatedReplyThreadKeystrokesResourceUser) {
        self.keys = keys
        self.user = user
    }


}
