//
// CreateTextMessageResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateTextMessageResource: Codable {

    public var type: String
    /** Optional string to associate this message with other messages. Can be used to group messages into a gallery */
    public var groupTag: String?
    /** Custom data associated with this message */
    public var properties: AnyCodable?
    public var user: Any?
    /** The text body of this message */
    public var body: String

    public init(type: String, groupTag: String? = nil, properties: AnyCodable? = nil, user: Any? = nil, body: String) {
        self.type = type
        self.groupTag = groupTag
        self.properties = properties
        self.user = user
        self.body = body
    }


}
