//
// CreatePersonChatUserResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreatePersonChatUserResource: Codable {

    /** Human readable name of this user. Shown to other users */
    public var displayName: String
    /** True if this user was created by a guest user session */
    public var isGuest: Bool
    /** The unique name used to identify this user across ChatKitty. Also known as username */
    public var name: String
    /** Custom data associated with this user */
    public var properties: AnyCodable?

    public init(displayName: String, isGuest: Bool, name: String, properties: AnyCodable? = nil) {
        self.displayName = displayName
        self.isGuest = isGuest
        self.name = name
        self.properties = properties
    }


}
