//
// CreateExternalFileProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateExternalFileProperties: Codable {

    /** File MIME content type */
    public var contentType: String
    /** File name */
    public var name: String
    /** File size in bytes */
    public var size: Int64
    /** External file URL */
    public var url: String

    public init(contentType: String, name: String, size: Int64, url: String) {
        self.contentType = contentType
        self.name = name
        self.size = size
        self.url = url
    }


}
