//
// CreateChannelInviteResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateChannelInviteResource: Codable {

    public var user: OneOfCreateChannelInviteResourceUser

    public init(user: OneOfCreateChannelInviteResourceUser) {
        self.user = user
    }


}
