//
// CursorPagedModelNotificationResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CursorPagedModelNotificationResourceEmbedded: Codable {

    public var notifications: [NotificationResource]?

    public init(notifications: [NotificationResource]? = nil) {
        self.notifications = notifications
    }


}
