//
// CursorPagedModelMessageResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CursorPagedModelMessageResourceEmbedded: Codable {

    public var messages: [MessageResource]?

    public init(messages: [MessageResource]? = nil) {
        self.messages = messages
    }


}
