//
// CursorPageMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CursorPageMetadata: Codable {

    public var next: String?
    public var size: Int64
    public var start: String?

    public init(next: String? = nil, size: Int64, start: String? = nil) {
        self.next = next
        self.size = size
        self.start = start
    }


}
