//
// CursorPagedModelNotificationResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CursorPagedModelNotificationResource: Codable {

    public var embedded: CursorPagedModelNotificationResourceEmbedded?
    public var page: CursorPageMetadata
    public var links: Links?

    public init(embedded: CursorPagedModelNotificationResourceEmbedded? = nil, page: CursorPageMetadata, links: Links? = nil) {
        self.embedded = embedded
        self.page = page
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case embedded = "_embedded"
        case page
        case links = "_links"
    }

}
