//
// DirectChannelProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A direct channel */

public struct DirectChannelProperties: Codable {

    public enum ModelType: String, Codable { 
        case direct = "DIRECT"
        case _public = "PUBLIC"
        case _private = "PRIVATE"
    }
    /** The type of this channel */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The ISO date-time this channel was created */
    public var createdTime: Date
    public var creator: ChatUserProperties?
    public var lastReceivedMessage: MessageProperties?
    /** The members of this channel. Present if this is a direct channel. For other channel types, use [**list channel messages**](https://chatkitty.com/docs/api/reference#tag/channels/operation/list-channel-messages) */
    public var members: [ChatUserProperties]
    /** Custom data associated with this channel */
    public var properties: AnyCodable

    public init(type: ModelType, _id: Int64, createdTime: Date, creator: ChatUserProperties? = nil, lastReceivedMessage: MessageProperties? = nil, members: [ChatUserProperties], properties: AnyCodable) {
        self.type = type
        self._id = _id
        self.createdTime = createdTime
        self.creator = creator
        self.lastReceivedMessage = lastReceivedMessage
        self.members = members
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case createdTime
        case creator
        case lastReceivedMessage
        case members
        case properties
    }

}
