//
// EmojiProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The emoji these users reacted with */

public struct EmojiProperties: Codable {

    /** List of possible aliases for this emoji */
    public var aliases: [String]
    /** The unicode character of this emoji */
    public var character: String
    /** Description of this emoji */
    public var _description: String
    /** Tags used to describe this emoji */
    public var tags: [String]

    public init(aliases: [String], character: String, _description: String, tags: [String]) {
        self.aliases = aliases
        self.character = character
        self._description = _description
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey { 
        case aliases
        case character
        case _description = "description"
        case tags
    }

}
