//
// FileProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The file data of this message */

public struct FileProperties: Codable {

    public enum ModelType: String, Codable { 
        case hosted = "HOSTED"
        case external = "EXTERNAL"
    }
    /** The type of this file. Either external or hosted by ChatKitty */
    public var type: ModelType
    /** The mime type of this file */
    public var contentType: String
    /** The file name */
    public var name: String
    /** The size of this file in bytes */
    public var size: Int64
    /** The file URL */
    public var url: String

    public init(type: ModelType, contentType: String, name: String, size: Int64, url: String) {
        self.type = type
        self.contentType = contentType
        self.name = name
        self.size = size
        self.url = url
    }


}
