//
// IdMessagesBody1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IdMessagesBody1: Codable {

    public var file: Data
    public var groupTag: String?
    public var username: String?
    public var properties: String?

    public init(file: Data, groupTag: String? = nil, username: String? = nil, properties: String? = nil) {
        self.file = file
        self.groupTag = groupTag
        self.username = username
        self.properties = properties
    }


}
