//
// IdMessagesBody3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IdMessagesBody3: Codable {

    public var file: Data
    public var groupTag: String?
    public var properties: String?

    public init(file: Data, groupTag: String? = nil, properties: String? = nil) {
        self.file = file
        self.groupTag = groupTag
        self.properties = properties
    }


}
