//
// ImportsChannelsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImportsChannelsBody: Codable {

    /** JSON array file with channels */
    public var file: Data

    public init(file: Data) {
        self.file = file
    }


}
