//
// MessageLinkPreviewImageProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Image data of this link preview */

public struct MessageLinkPreviewImageProperties: Codable {

    /** The url source of this image */
    public var source: String

    public init(source: String) {
        self.source = source
    }


}
