//
// MessageLinkProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Link previews in this message */

public struct MessageLinkProperties: Codable {

    /** The ending index of this link within the message */
    public var endPosition: Int
    public var preview: MessageLinkPreviewProperties?
    /** The href of the URL this message link represents */
    public var source: String
    /** The starting index of this link within the message */
    public var startPosition: Int

    public init(endPosition: Int, preview: MessageLinkPreviewProperties? = nil, source: String, startPosition: Int) {
        self.endPosition = endPosition
        self.preview = preview
        self.source = source
        self.startPosition = startPosition
    }


}
