//
// MessageReadReceiptResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageReadReceiptResource: Codable {

    /** Time the user read this message */
    public var createdTime: Date
    public var user: ChatUserProperties
    public var links: Links?

    public init(createdTime: Date, user: ChatUserProperties, links: Links? = nil) {
        self.createdTime = createdTime
        self.user = user
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case createdTime
        case user
        case links = "_links"
    }

}
