//
// MessagePropertiesPatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessagePropertiesPatch: Codable {

    /** Updates the text body of this message */
    public var body: String?
    /** Updates custom data associated with this message */
    public var properties: AnyCodable?

    public init(body: String? = nil, properties: AnyCodable? = nil) {
        self.body = body
        self.properties = properties
    }


}
