//
// MessageLinkPreviewProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Embedded link preview data */

public struct MessageLinkPreviewProperties: Codable {

    /** Description of this link preview */
    public var _description: String?
    public var image: MessageLinkPreviewImageProperties
    /** The name of the site linked */
    public var siteName: String?
    /** The title of this link */
    public var title: String
    /** The URL of the link being previewed */
    public var url: String

    public init(_description: String? = nil, image: MessageLinkPreviewImageProperties, siteName: String? = nil, title: String, url: String) {
        self._description = _description
        self.image = image
        self.siteName = siteName
        self.title = title
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case image
        case siteName
        case title
        case url
    }

}
