//
// NotificationResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotificationResource: Codable {

    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The text body of this notification */
    public var body: String
    public var channel: OneOfNotificationResourceChannel?
    /** Time this notification was created */
    public var createdTime: Date
    public var data: NotificationData
    /** True if this notification should be muted */
    public var muted: Bool
    /** Time this notification was read */
    public var readTime: Date?
    /** The title of this notification */
    public var title: String
    public var links: Links?

    public init(_id: Int64, body: String, channel: OneOfNotificationResourceChannel? = nil, createdTime: Date, data: NotificationData, muted: Bool, readTime: Date? = nil, title: String, links: Links? = nil) {
        self._id = _id
        self.body = body
        self.channel = channel
        self.createdTime = createdTime
        self.data = data
        self.muted = muted
        self.readTime = readTime
        self.title = title
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case body
        case channel
        case createdTime
        case data
        case muted
        case readTime
        case title
        case links = "_links"
    }

}
