//
// NotificationData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Additional context data of this notification */

public struct NotificationData: Codable {

    /** The type of notification that was received. This specifies the schema of the notification data */
    public var type: String

    public init(type: String) {
        self.type = type
    }


}
