//
// PagedModelChatUserSessionResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChatUserSessionResourceEmbedded: Codable {

    public var sessions: [ChatUserSessionResource]?

    public init(sessions: [ChatUserSessionResource]? = nil) {
        self.sessions = sessions
    }


}
