//
// PagedModelChatSessionResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChatSessionResourceEmbedded: Codable {

    public var sessions: [ChatSessionResource]?

    public init(sessions: [ChatSessionResource]? = nil) {
        self.sessions = sessions
    }


}
