//
// PagedModelChatUserResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChatUserResourceEmbedded: Codable {

    public var users: [ChatUserResource]?

    public init(users: [ChatUserResource]? = nil) {
        self.users = users
    }


}
