//
// PagedModelMessageReadReceiptResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelMessageReadReceiptResourceEmbedded: Codable {

    public var receipts: [MessageReadReceiptResource]?

    public init(receipts: [MessageReadReceiptResource]? = nil) {
        self.receipts = receipts
    }


}
