//
// PagedModelApplicationJobResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelApplicationJobResourceEmbedded: Codable {

    public var jobs: [ApplicationJobResource]?

    public init(jobs: [ApplicationJobResource]? = nil) {
        self.jobs = jobs
    }


}
