//
// PagedModelChatFunctionVersionResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChatFunctionVersionResourceEmbedded: Codable {

    public var versions: [ChatFunctionVersionResource]?

    public init(versions: [ChatFunctionVersionResource]? = nil) {
        self.versions = versions
    }


}
