//
// PagedModelChatFunctionResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChatFunctionResourceEmbedded: Codable {

    public var functions: [ChatFunctionResource]?

    public init(functions: [ChatFunctionResource]? = nil) {
        self.functions = functions
    }


}
