//
// PagedModelChannelInviteResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChannelInviteResourceEmbedded: Codable {

    public var invites: [ChannelInviteResource]?

    public init(invites: [ChannelInviteResource]? = nil) {
        self.invites = invites
    }


}
