//
// PagedModelChatFunctionInvocationResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChatFunctionInvocationResourceEmbedded: Codable {

    public var invocations: [ChatFunctionInvocationResource]?

    public init(invocations: [ChatFunctionInvocationResource]? = nil) {
        self.invocations = invocations
    }


}
