//
// PagedModelChannelResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChannelResourceEmbedded: Codable {

    public var channels: [ChannelResource]?

    public init(channels: [ChannelResource]? = nil) {
        self.channels = channels
    }


}
