//
// PagedModelChannelMembershipResourceEmbedded.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PagedModelChannelMembershipResourceEmbedded: Codable {

    public var memberships: [ChannelMembershipResource]?

    public init(memberships: [ChannelMembershipResource]? = nil) {
        self.memberships = memberships
    }


}
