//
// PublicChannelImport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Imports a public channel */

public struct PublicChannelImport: Codable {

    public var type: String
    /** Username of the user who created this channel */
    public var creator: String?
    /** Unique value generated by the client which ChatKitty uses to recognize subsequent retries of the same request. Optional but recommended */
    public var idempotencyKey: String?
    /** List of usernames of members of this channel */
    public var members: [String]
    /** Custom data associated with this channel */
    public var properties: AnyCodable?
    /** The unique name of this channel used to reference the channel. If absent defaults to a random UUID */
    public var name: String?
    /** Human readable name of this channel shown to users. If absent defaults to the channel name */
    public var displayName: String?

    public init(type: String, creator: String? = nil, idempotencyKey: String? = nil, members: [String], properties: AnyCodable? = nil, name: String? = nil, displayName: String? = nil) {
        self.type = type
        self.creator = creator
        self.idempotencyKey = idempotencyKey
        self.members = members
        self.properties = properties
        self.name = name
        self.displayName = displayName
    }


}
