//
// PublicChannelProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A public channel */

public struct PublicChannelProperties: Codable {

    public enum ModelType: String, Codable { 
        case direct = "DIRECT"
        case _public = "PUBLIC"
        case _private = "PRIVATE"
    }
    /** The type of this channel */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The ISO date-time this channel was created */
    public var createdTime: Date
    public var creator: ChatUserProperties?
    /** Human readable name of this channel shown to users */
    public var displayName: String
    public var lastReceivedMessage: MessageProperties?
    /** The unique name of this channel used to reference the channel */
    public var name: String
    /** Custom data associated with this channel */
    public var properties: AnyCodable

    public init(type: ModelType, _id: Int64, createdTime: Date, creator: ChatUserProperties? = nil, displayName: String, lastReceivedMessage: MessageProperties? = nil, name: String, properties: AnyCodable) {
        self.type = type
        self._id = _id
        self.createdTime = createdTime
        self.creator = creator
        self.displayName = displayName
        self.lastReceivedMessage = lastReceivedMessage
        self.name = name
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case createdTime
        case creator
        case displayName
        case lastReceivedMessage
        case name
        case properties
    }

}
