//
// ReplyThreadResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReplyThreadResource: Codable {

    public enum ModelType: String, Codable { 
        case main = "MAIN"
        case standalone = "STANDALONE"
        case message = "MESSAGE"
    }
    /** The type of this thread */
    public var type: ModelType
    /** 64-bit integer identifier associated with this resource */
    public var _id: Int64
    /** The ISO date-time this thread was created */
    public var createdTime: Date
    /** The name of this thread */
    public var name: String?
    /** Custom data associated with this thread */
    public var properties: AnyCodable
    public var links: Links?

    public init(type: ModelType, _id: Int64, createdTime: Date, name: String? = nil, properties: AnyCodable, links: Links? = nil) {
        self.type = type
        self._id = _id
        self.createdTime = createdTime
        self.name = name
        self.properties = properties
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case createdTime
        case name
        case properties
        case links = "_links"
    }

}
