//
// ReplyThreadKeystrokesResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReplyThreadKeystrokesResource: Codable {

    public var keys: String
    public var username: String
    public var links: Links?

    public init(keys: String, username: String, links: Links? = nil) {
        self.keys = keys
        self.username = username
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case keys
        case username
        case links = "_links"
    }

}
