//
// SecretResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SecretResource: Codable {

    /** Secret value */
    public var secret: Any?

    public init(secret: Any? = nil) {
        self.secret = secret
    }


}
