//
// TextChatUserMessageImport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Imports a user text message */

public struct TextChatUserMessageImport: Codable {

    public var type: String
    /** ID of the channel this message belongs to */
    public var channelId: Int64
    /** Tag identifying the message group this message belongs to */
    public var groupTag: String?
    /** Unique value generated by the client which ChatKitty uses to recognize subsequent retries of the same request. Optional but recommended */
    public var idempotencyKey: String?
    /** Map of custom data attached to this message */
    public var properties: AnyCodable?
    /** The text body of this message */
    public var body: String
    /** Username of the user who sent this message */
    public var user: String

    public init(type: String, channelId: Int64, groupTag: String? = nil, idempotencyKey: String? = nil, properties: AnyCodable? = nil, body: String, user: String) {
        self.type = type
        self.channelId = channelId
        self.groupTag = groupTag
        self.idempotencyKey = idempotencyKey
        self.properties = properties
        self.body = body
        self.user = user
    }


}
