//
// TextMessageImport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TextMessageImport: Codable {

    /** The text body of this message */
    public var body: String
    /** ID of the channel this message belongs to */
    public var channelId: Int64
    /** Tag identifying the message group this message belongs to */
    public var groupTag: String?
    /** Unique value generated by the client which ChatKitty uses to recognize subsequent retries of the same request. Optional but recommended */
    public var idempotencyKey: String?
    /** Map of custom data attached to this message */
    public var properties: AnyCodable?

    public init(body: String, channelId: Int64, groupTag: String? = nil, idempotencyKey: String? = nil, properties: AnyCodable? = nil) {
        self.body = body
        self.channelId = channelId
        self.groupTag = groupTag
        self.idempotencyKey = idempotencyKey
        self.properties = properties
    }


}
